# Generated by Django 3.0.2 on 2020-02-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0002_auto_20200209_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='logo',
            field=models.ImageField(default='default_logo.jpg', upload_to='doctor_logo'),
        ),
    ]
