# Generated by Django 3.0.2 on 2020-03-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0005_patient_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
