# Generated by Django 3.0.2 on 2020-04-26 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0007_expense_expensetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='mobile',
            new_name='mobile1',
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile2',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919999999'", regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
    ]
